// ESLint flat config for the m365-owa-tb Thunderbird WebExtension.
// Browser/WebExtension globals + ES2022. No type-checking (no TS).
export default [
  {
    files: ["**/*.{js,mjs}"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        // WebExtension / Thunderbird globals
        browser: "readonly",
        messenger: "readonly",
        particlesJS: "readonly",
        pJSDom: "readonly",
        window: "readonly",
        document: "readonly",
        console: "readonly",
        fetch: "readonly",
        XMLHttpRequest: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        Blob: "readonly",
        Image: "readonly",
        DOMParser: "readonly",
        XMLSerializer: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        FormData: "readonly",
        Headers: "readonly",
        Request: "readonly",
        Response: "readonly",
        atob: "readonly",
        btoa: "readonly",
        crypto: "readonly",
        globalThis: "readonly",
        location: "readonly",
        navigator: "readonly",
        self: "readonly",
        structuredClone: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        localStorage: "readonly",
        // Cross-file globals shared across background scripts (TB loads
        // all background scripts into one shared scope, so these top-level
        // vars are visible to each other but eslint sees each file in isolation)
        CONFIG: "readonly",
        Auth: "readonly",
        OWA: "readonly",
        VCard: "readonly",
        JCal: "readonly",
        CalendarSync: "readonly",
        ContactsSync: "readonly",
        loadConfig: "readonly",
        _JCalComp: "readonly",
      },
    },
    rules: {
      // Lenient but useful — catches real bugs without blocking on style
      "no-undef": "error",
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "no-redeclare": "error",
      "no-constant-condition": "warn",
      "no-debugger": "error",
      "no-dupe-keys": "error",
      "no-empty": "warn",
      "no-irregular-whitespace": "error",
      "no-useless-escape": "warn",
      "prefer-const": "warn",
      "no-var": "warn",
      "eqeqeq": ["warn", "smart"],
    },
    ignores: [
      "**/node_modules/**",
      "**/*.min.js",
      "experiments/**",
      "options_ui/particles.min.js",
    ],
  },
];
